#!/bin/bash

# all rpi has mac b8:27:eb as the start of their mac
piaddr=$( arp -na | grep -i b8:27:eb | xargs -L1 sh -c 'echo $1' )
bin=$1
echo $bin
for ip in $piaddr; do
  #remove the parentheses
  ip=$(echo $ip | sed s/\(//g)
  ip=$(echo $ip | sed s/\)//g)
  #ip is now a pure ip address, use that for flashing
  arm-none-eabi-gdb $bin -q -ex "set confirm off" -ex "target extended-remote $ip:3333" -ex "monitor swdp_scan" -ex "attach 1"  -ex "load" -ex "kill" -ex "quit"
  echo "$ip"
done
