# Api config files, use `api_key` or `api_key_command` fields
# to set the api key for each api
# more details at https://github.com/efugier/smartcat#configuration

[groq]
url = "https://api.groq.com/openai/v1/chat/completions"
default_model = "llama3-70b-8192"

[anthropic]
url = "https://api.anthropic.com/v1/messages"
default_model = "claude-3-opus-20240229"
version = "2023-06-01"

[azureopenai]
url = "https://your-azure-endpoint.azure.com/openai/deployments/your-deployment-id/chat/completions?api-version=2024-06-01"
default_model = "gpt-4o"

[openai]
url = "https://api.openai.com/v1/chat/completions"
default_model = "gpt-4"

[mistral]
url = "https://api.mistral.ai/v1/chat/completions"
default_model = "mistral-medium"

[ollama]
url = "http://10.42.10.8:11434/api/chat"
# default_model = "deepseek-r1:14b"
default_model = "qwen2.5-coder:14b"
timeout_seconds = 180
